# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"31.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1406067255000,\"rdfTime\":1405936974000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1405937701000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"mtime\":1405938263000}}}]");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "2d20e061-07de-4b82-bd05-b9e672aed0b");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
